### ISSUE TITLE
Sort uses 819⌶, is therefore not ready for 20.0

### ISSUE THREAD

**Issue by aplteam** [abrudz/Sort#2]

**Comment by abrudz** [comment]
I don't understand how its mention of `819⌶` means it isn't ready for 20.0. Can you explain?

**Comment by aplteam** [comment]
I searched thru all my projects, forked and otherwise, for 819, assuming that when I find `819⌶` somewhere it's not  ready for 20.0 yet. I was wrong, sorry.
